---
title: "Academic Research and Teaching"
---
<!-- Google tag (gtag.js) -->
<script async src="https://www.googletagmanager.com/gtag/js?id=G-C9REN6Q65E"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-C9REN6Q65E');
</script>


<style>
body {
text-align: justify}
</style>

<br>
<a href="https://www.dropbox.com/s/eaezc5lrlj0vq30/CV.pdf?dl=0">For my recent resume, please click here. </a>

<DIV STYLE="background-color:#000000; height:0.5px; width:100%;">

<br>

<p style="color:black"> <b> RESEARCH </b> My research tries to undercover psychobiological underpinnings of key political attitudes and behavior, such as conservatism, political participation, partisan animosities, democracy satisfaction, and anti-immigration, in a multilevel perspective (across countries and years). Accordingly, I have been trying to advance theoretically informed and methodologically robust lines of political science research, benefiting from  (i) national and cross-national face-to-face and online survey (experiment) data, supplemented with the twins sub-sample, genetic risk scores for the relevant attitudes and behavior, and physiological measures, (ii) quasi-experimental designs (i.e., propensity score matching, instrumental variable estimator, the difference-in-differences approach, and lagged dependent variable models), (iii) various advanced quantitative research methods, such as categorical data analysis, multilevel modeling (with post-stratification), and structural equation modeling (SEM), which can further be used for robust cross-sectional and longitudinal data analyses, and (iv) text-as-data methods (i.e., Wordscores and Latent Semantic Scaling) helping me infer the particular orientation of leaders and ordinary citizens based on various qualitative data, such as government bills, press releases, speeches, tweets, and open-ended survey responses, as (in)dependent and/or control variables for associational and quasi-experimental analyses. Though the units of analysis in my research tend to be individual survey and survey experiment respondents, I am also accustomed to working with and using various international relations datasets (such as the Correlates of War Project datasets, Global Terrorism Database, World Bank Open Data, and Stockholm International Peace Research Institute Databases, and many others) in my research and teaching efforts. </p>

<DIV STYLE="background-color:#000000; height:0.5px; width:100%;">

<br>
<p style="color:black"> <b> TEACHING </b> Across all levels of teaching (at the introductory level, in upper-level seminars, or at the graduate level), my primary focus is on encouraging students to add a scientific approach to politics to their intellectual toolbox. This means, first, promoting students’ scientific literacy by teaching students how social science is distinct from journalistic and rhetorical approaches to politics, by aiming to uncover systematic truths about politics rather than accounting for a single event or persuading to a point of view. Second, teaching political science means demonstrating the value of a scientific approach to politics, both in creating understanding for its own sake and as an important complement to normative reasoning in crafting effective public policy. Finally, a scientific approach to politics involves teaching students to do science individually and collaboratively. The list of courses that involve ongoing learning and experimentation to improve my teaching methods as per these three elements is as follows: </p>

<ul style="color:black" >

  <li> University of Arizona - Spring 2024: POL/SOC 297B The Origins of Data in Politics and Policy (Undergraduate) (<a href="https://www.dropbox.com/scl/fi/cv2aq8wg4nmq9qfiopdrr/POL-297B-Spring-2024.pdf?rlkey=95eaka1wvv4x3c8vhzx7biu60&dl=0">[syllabus]</a>) </li>

  <li> Yeditepe University - Spring 2023: POLS 624 Quantitative Methods and Statistics (Graduate) (<a href="https://www.dropbox.com/scl/fi/ybzxwt328ab1zkvpy9oiu/POLS-624-Syllabus.pdf?rlkey=ato45qj0y3ax0isp71xfaavlp&dl=0">[syllabus]</a>) </li>

  <li> Yeditepe University - Spring 2023: PSIR 480 Applied Research in Political Science (Undergraduate) (Undergraduate) (<a href="https://www.dropbox.com/scl/fi/jxp2f8ielqovykootneyn/PSIR_480.pdf?rlkey=dbl9hw36nprv4wtkgrz4ew5km&dl=0">[syllabus]</a>) </li>

  <li> Yeditepe University - Fall 2022, Spring 2023: RSCH 410 Scientific Research Methods (Undergraduate)  (<a>[the service-course syllabus not shared]</a>) </li>

  <li> Yeditepe University - Fall 2022, Spring 2023: PSIR 101 Introduction to Political Science (Undergraduate) (<a href="https://www.dropbox.com/scl/fi/vw9pta6uzl7il4d1dr363/PSIR_101.pdf?rlkey=6sc91oq3wxgf2e5u42m48i0og&dl=0">[syllabus]</a>) </li>

  <li> Istanbul Bilgi University - Fall 2021: IR 408 Elections and Party Politics (Undergraduate) (<a href="https://www.dropbox.com/scl/fi/qjkl5hj6h591foiinirnf/IR408-Fall-2021-Syllabus.pdf?rlkey=mx2pusj3hy0t95mmyvys72zzs&dl=0">[syllabus]</a>) </li>

</ul>




<DIV STYLE="background-color:#000000; height:0.5px; width:100%;">

<br>
<p style="color:black"> <b> DIVERSITY, INCLUSION, AND BELONGING </b> Studies show that political science (despite its crucial function in comprehending and influencing our societies) is one of the least diverse fields of study in higher education (see <a href="https://doi.org/10.1017/S1049096518000513">[1]</a>, <a href="https://doi.org/10.1017/S1049096518002068">[2]</a>, <a href="https://www.cambridge.org/core/journals/ps-political-science-and-politics/article/abs/leveraging-diversity-in-political-science-for-institutional-and-disciplinary-change/C6F738E3B333BF98DFB75FB6D7383780">[3]</a>). Hence, I have been paying close attention to the American Political Science Association's Diversity and Inclusion Resources (see <a href="https://www.apsanet.org/divresources">[here]</a>) to foster a more diverse, inclusive and equitable academic environment for research and teaching. Then, to address this challenge to the best of resources (time, energy, and administrative power) at my hand, I have been (i) avoiding citation gaps in my research's bibliographies and courses' syllabi (based on author gender and region), (ii) collaborating with a diverse pool of scholars (faculty members, graduate and undergraduate students) and, if possible, asking them to be the lead authors, (iii) guiding the graduate and undergraduate students about the summer and winter research methods schools and convention participation scholarships for the marginalized members of the academia, and (iv) assisting in providing access to mental health care and well-being support for those in need. </p> 

<br>

<!--
<button class="btn btn-primary" data-toggle="collapse" data-target="#Spectra">To access to my recent resume, please click.</button> 
<div id="Spectra" class="collapse">    
<object data="CV.pdf" width="750px" height="750px">
    <embed src="CV.pdf">
    </embed>
</object>
</div>
--> 
